version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell

formatters:
  enable:
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/danjdewhurst/envio

linters-settings:
  misspell:
    locale: US

issues:
  exclude-use-default: false
